set(CMAKE_VS_DEBUGGER_WORKING_DIRECTORY "${CMAKE_BINARY_DIR}/ERM" CACHE PATH "" FORCE)
set(CMAKE_CONFIGURATION_TYPES "Debug;Release" CACHE STRING "" FORCE)
set(ERM_CMAKE_GENERATOR "VS" CACHE STRING "" FORCE)
set(ERM_GENERATOR_VS ON CACHE BOOL "" FORCE)
