set(CMAKE_XCODE_SCHEME_WORKING_DIRECTORY "${CMAKE_BINARY_DIR}/ERM" CACHE PATH "" FORCE)
set(CMAKE_CONFIGURATION_TYPES "Debug;Release" CACHE STRING "" FORCE)
set(ERM_CMAKE_GENERATOR "XCODE" CACHE STRING "" FORCE)
set(ERM_GENERATOR_XCODE ON CACHE BOOL "" FORCE)