#pragma once

namespace erm {

	enum class ImageLayout
	{
		UNDEFINED,
		COLOR_ATTACHMENT_OPTIMAL,
		DEPTH_ATTACHMMENT_OPTIMAL,
		DEPTH_READONLY_OPTIMAL,
		DEPTH_STENCIL_ATTACHMENT_OPTIMAL,
		DEPTH_STENCIL_READONLY_OPTIMAL,
		STENCIL_ATTACHMENT_OPTIMAL,
		STENCIL_READONLY_OPTIMAL,
		PRESENT_SRC,
		GENERAL
	};

}
