set(ERM_OPEN_GL ON CACHE BOOL "" FORCE)
set(ERM_RENDERING_API_COMPILE_DEF "ERM_OPEN_GL" CACHE STRING "" FORCE)
find_package(OpenGL REQUIRED)
set(ERM_RENDERING_API_LIB "${OPENGL_gl_LIBRARY}" CACHE STRING "" FORCE)
