set(ERM_DX12 ON CACHE BOOL "" FORCE)
set(ERM_RENDERING_API_COMPILE_DEF "ERM_DX12" CACHE STRING "" FORCE)
find_package(DX12 REQUIRED)
set(ERM_RENDERING_API_LIB "${DX12_Libraries}" CACHE STRING "" FORCE)
