#pragma once

#include <erm/utils/Flags.h>
#include <erm/utils/Macros.h>

namespace erm {

#ifdef ERM_RAY_TRACING_ENABLED
ERM_ENUM_WITH_FLAGS(
	BufferUsage,
	TRANSFER_SRC = 1,
	TRANSFER_DST = 2,
	UNIFORM_BUFFER = 4,
	STORAGE_BUFFER = 8,
	INDEX_BUFFER = 16,
	VERTEX_BUFFER = 32,
	SHADER_DEVICE_ADDRESS = 64,
	ACCELERATION_STRUCTURE_BUILD_INPUT_READ_ONLY = 128,
	ACCELERATION_STRUCTURE_STORAGE = 256,
	SHADER_BINDING_TABLE = 512)
#else
ERM_ENUM_WITH_FLAGS(
	BufferUsage,
	TRANSFER_SRC = 1,
	TRANSFER_DST = 2,
	UNIFORM_BUFFER = 4,
	STORAGE_BUFFER = 8,
	INDEX_BUFFER = 16,
	VERTEX_BUFFER = 32,
	SHADER_DEVICE_ADDRESS = 64)
#endif

} // namespace erm