if("${CMAKE_CXX_COMPILER_ID}" STREQUAL "MSVC")
    include(cmake/compilers/ERMMSVC.cmake)
elseif("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang")
    include(cmake/compilers/ERMClang.cmake)
elseif("${CMAKE_CXX_COMPILER_ID}" STREQUAL "AppleClang")
    include(cmake/compilers/ERMAppleClang.cmake)
else()
    message(FATAL_ERROR "CXX Compiler not supported {CMAKE_CXX_COMPILER_ID}")
endif()

message(STATUS "Using ${CMAKE_CXX_COMPILER_ID} compiler")