function(setup_api)
	if("${TARGET_API}" STREQUAL "OpenGl")
		set(TARGET_API_COMPILE_DEF "ERM_OPENGL" PARENT_SCOPE)
		find_package(OpenGL REQUIRED)
		set(TARGET_API_LIB "${OPENGL_gl_LIBRARY}" PARENT_SCOPE)
	elseif("${TARGET_API}" STREQUAL "Vulkan" OR NOT "${TARGET_API}")
		set(TARGET_API "Vulkan" PARENT_SCOPE)
		set(TARGET_API_COMPILE_DEF "ERM_VULKAN" PARENT_SCOPE)
		find_package(Vulkan REQUIRED)
		set(TARGET_API_LIB "${Vulkan_LIBRARIES}" PARENT_SCOPE)
		set(TARGET_API_INCLUDE_DIR "${Vulkan_INCLUDE_DIR}" PARENT_SCOPE)
		set(GLFW_VULKAN_STATIC TRUE PARENT_SCOPE)
	else()
		message(FATAL_ERROR "Target API ${TARGET_API} not supported")
	endif()
endfunction()

option(ERM_FLIP_PROJECTION "If TRUE the projection matrix will be flipped over the Y axis" ON)
option(ERM_FLIP_VIEWPORT "If TRUE the viewport will be flipped over the Y axis" OFF)
