function(setup_api)
	if("${TARGET_API}" STREQUAL "OpenGl" OR NOT "${TARGET_API}")
		set(TARGET_API "OpenGl")
		find_package("${TARGET_API}" REQUIRED)
		set(TARGET_API_LIB "${OPENGL_gl_LIBRARY}" PARENT_SCOPE)
	else()
		message(FATAL_ERROR "Target API ${TARGET_API} not supported")
	endif()
	message(STATUS "Using ${TARGET_API} API")
endfunction()