if("${CMAKE_CXX_COMPILER_ID}" STREQUAL "MSVC")
    set(ERM_MSVC ON CACHE BOOL "" FORCE)
    include(ERMMSVC)
elseif("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang")
    set(ERM_CLANG ON CACHE BOOL "" FORCE)
    include(ERMClang)
elseif("${CMAKE_CXX_COMPILER_ID}" STREQUAL "AppleClang")
    set(ERM_APPLE_CLANG ON CACHE BOOL "" FORCE)
    include(ERMAppleClang)
else()
    message(FATAL_ERROR "CXX Compiler not supported {CMAKE_CXX_COMPILER_ID}")
endif()

message(STATUS "Using ${CMAKE_CXX_COMPILER_ID} compiler")