if("${CMAKE_GENERATOR}" STREQUAL "Xcode")
    include(cmake/generators/ERMGeneratorXcode.cmake)
elseif("${CMAKE_GENERATOR}" STREQUAL "Visual Studio 18 2026")
    include(cmake/generators/ERMGeneratorVS.cmake)
elseif("${CMAKE_GENERATOR}" STREQUAL "Ninja")
    include(cmake/generators/ERMGeneratorNinja.cmake)
elseif("${CMAKE_GENERATOR}" STREQUAL "Unix Makefiles")
    include(cmake/generators/ERMGeneratorUnixMK.cmake)
else()
	message(FATAL_ERROR "CMake generator not supported: ${CMAKE_GENERATOR}")
endif()

message(STATUS "Using ${ERM_CMAKE_GENERATOR} generator")