if("${CMAKE_HOST_SYSTEM_NAME}" STREQUAL "Windows")
    include(cmake/host_platforms/ERMHostWin.cmake)
elseif("${CMAKE_HOST_SYSTEM_NAME}" STREQUAL "Darwin")
    include(cmake/host_platforms/ERMHostOSX.cmake)
elseif("${CMAKE_HOST_SYSTEM_NAME}" STREQUAL "Linux")
    include(cmake/host_platforms/ERMHostLinux.cmake)
else()
	message(FATAL_ERROR "Host platform not supported: ${CMAKE_HOST_SYSTEM_NAME}")
endif()

message(STATUS "Detected ${ERM_HOST_PLATFORM} host platform")
