function(erm_gather_directories OUT_VAR)
	file(GLOB GLOBBED_FILES LIST_DIRECTORIES true *)
	foreach(FILE ${GLOBBED_FILES})
		if(IS_DIRECTORY "${FILE}")
			list(APPEND DIRECTORIES ${FILE})
		endif()
	endforeach()
	set("${OUT_VAR}" ${DIRECTORIES} PARENT_SCOPE)
endfunction()

function(erm_get_dir_name_from_path DIR_PATH)
	if(NOT IS_DIRECTORY "${DIR_PATH}")
		message(FATAL_ERROR "No such directory: ${DIR_PATH}")
	endif()
	cmake_path(GET DIR_PATH STEM DIR_NAME)
	set(DIR_NAME ${DIR_NAME} PARENT_SCOPE)
endfunction()