#include "input/Mouse.h"

#include <GLFW/glfw3.h>

namespace erm {
	
	MouseButton MOUSE_BUTTON_1 = GLFW_MOUSE_BUTTON_1;
	MouseButton MOUSE_BUTTON_2 = GLFW_MOUSE_BUTTON_2;
	MouseButton MOUSE_BUTTON_3 = GLFW_MOUSE_BUTTON_3;
	MouseButton MOUSE_BUTTON_4 = GLFW_MOUSE_BUTTON_4;
	MouseButton MOUSE_BUTTON_5 = GLFW_MOUSE_BUTTON_5;
	MouseButton MOUSE_BUTTON_6 = GLFW_MOUSE_BUTTON_6;
	MouseButton MOUSE_BUTTON_7 = GLFW_MOUSE_BUTTON_7;
	MouseButton MOUSE_BUTTON_8 = GLFW_MOUSE_BUTTON_8;
	MouseButton MOUSE_BUTTON_LEFT = GLFW_MOUSE_BUTTON_LEFT;
	MouseButton MOUSE_BUTTON_RIGHT = GLFW_MOUSE_BUTTON_RIGHT;
	MouseButton MOUSE_BUTTON_MIDDLE = GLFW_MOUSE_BUTTON_MIDDLE;
	
}
